# TCL File Generated by Component Editor 17.0
# Wed Jan 12 18:12:24 CET 2022
# DO NOT MODIFY


# 
# rooms_manager "rooms_manager" v1.0
#  2022.01.12.18:12:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rooms_manager
# 
set_module_property DESCRIPTION ""
set_module_property NAME rooms_manager
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rooms_manager
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Lab6
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Lab7.vhd VHDL PATH Lab7.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk_clk
set_interface_property avalon_slave_0 associatedReset reset_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 8
add_interface_port avalon_slave_0 wr write Input 1
add_interface_port avalon_slave_0 cs chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clk_clk
set_interface_property conduit_end associatedReset reset_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end hexThree_out hex2 Output 7
add_interface_port conduit_end hexOne_out hex1 Output 7
add_interface_port conduit_end hexTwo_out hex3 Output 7
add_interface_port conduit_end leds_out leds_out Output 1


# 
# connection point reset_reset
# 
add_interface reset_reset reset end
set_interface_property reset_reset associatedClock clk_clk
set_interface_property reset_reset synchronousEdges DEASSERT
set_interface_property reset_reset ENABLED true
set_interface_property reset_reset EXPORT_OF ""
set_interface_property reset_reset PORT_NAME_MAP ""
set_interface_property reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property reset_reset SVD_ADDRESS_GROUP ""

add_interface_port reset_reset reset_reset reset Input 1


# 
# connection point clk_clk
# 
add_interface clk_clk clock end
set_interface_property clk_clk clockRate 0
set_interface_property clk_clk ENABLED true
set_interface_property clk_clk EXPORT_OF ""
set_interface_property clk_clk PORT_NAME_MAP ""
set_interface_property clk_clk CMSIS_SVD_VARIABLES ""
set_interface_property clk_clk SVD_ADDRESS_GROUP ""

add_interface_port clk_clk clk_clk clk Input 1

